FORMAT: 1A

# NIFD CMS API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Media
## Media Collection [/media/headMedia]
### get head medias [GET]

+ Response 200 (application/json)
        [{
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        },
        {
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        },
        {
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        },
        {
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        }]

## Expert Collection [/expert/information]
### Get all Experts [GET]

+ Response 200 (application/json)
        [{
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          }]
          
##About Collection [/about/contactUs]

### List All ExpertActivtiy [GET]

+ Response 200 (application/json)

        [
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        }
        ]
        
