FORMAT: 1A

# NIFD CMS API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Media
## Media Collection [/media/headMedia]
### get head medias [GET]

+ Response 200(application/json)
        [{
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        },
        {
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        },
        {
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        },
        {
            "id":1,
            "speaker ": "李杨",
            "title":"人民币国际化有利于国内金融市场改革",
            "media":"中国新闻网",
            "date":"2015.09.09",
            "pic": "img/24/3.jpg",
            "url":"http://www.chinanews.com"
        }]

## Expert Collection [/expert/information]
### Get all Experts [GET]

+ Response 200 (application/json)
        [{
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          },
          {
          "id":1,
          "name": "马汉传",
          "career":"科学家",
          "introduction": "马皮创始人",
          "pic": "img/experts/expert.png"
          }]

## Expert Collection [/expert/activity]

### List All ExpertActivtiy [GET]

+ Response 200 (application/json)

        [
        {"id":1,
        "expert": "张子涵",
        "title":"Google三号人物谈手机的滥用王兴公布美团上半年数据：超去年全年",
        "date":"2015.09.09",
        "pic": "img/experts/expert.png",
        "url":"http://www.baidu.com"
        },
        {"id":1,
        "expert": "张子涵",
        "title":"Google三号人物谈手机的滥用王兴公布美团上半年数据：超去年全年",
        "date":"2015.09.09",
        "pic": "img/experts/expert.png",
        "url":"http://www.baidu.com"
        },
        {"id":1,
        "expert": "张子涵",
        "title":"Google三号人物谈手机的滥用王兴公布美团上半年数据：超去年全年",
        "date":"2015.09.09",
        "pic": "img/experts/expert.png",
        "url":"http://www.baidu.com"
        },
        {"id":1,
        "expert": "张子涵",
        "title":"Google三号人物谈手机的滥用王兴公布美团上半年数据：超去年全年",
        "date":"2015.09.09",
        "pic": "img/experts/expert.png",
        "url":"http://www.baidu.com"
        },
        {"id":1,
        "expert": "张子涵",
        "title":"Google三号人物谈手机的滥用王兴公布美团上半年数据：超去年全年",
        "date":"2015.09.09",
        "pic": "img/experts/expert.png",
        "url":"http://www.baidu.com"
        }
        ]

##About Collection [/about/contactUs]

### List All ExpertActivtiy [GET]

+ Response 200 (application/json)

        [
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        },
        {"id":1,
        "department": "公关部",
        "email":"info-cn@nifd.com",
        "tel":"+86 4008 900 505",
        "pic": "img/experts/expert.png"
        }
        ]
        

## About Collection [/about/details]

### List All About [GET]

+ Response 200 (application/json)

        {
        "overview":"专业关注度的创业项目线下孵化器。自2014年4月份上线以来，报名申请入驻氪空间的创业项目超过5000个。到2014年10月为止，已有29家团队入驻过氪空间。第一批项目共12个，其中11个完成融资并孵化成功。全部项目总融资额达到5000万人民币，最大单笔融资1000万，入住后平均融资周期仅为1个月。",
        "institution": "专业关注度的创业项目线下孵化器。自2014年4月份上线以来，报名申请入驻氪空间的创业项目超过5000个。到2014年10月为止，已有29家团队入驻过氪空间。第一批项目共12个，其中11个完成融资并孵化成功。全部项目总融资额达到5000万人民币，最大单笔融资1000万，入住后平均融资周期仅为1个月。",
        "location":"北京建国门内大街5号中国社会科学院",
        "pic_about": "img/experts/expert.png",
        "pic_location":"img/experts/expert.png"
        }
        
